//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screw
    {
        public int ID { get; set; }
        public string sName { get; set; }
        public override string ToString()
        {
            return ID + " " + sName;
        }
    }
}
